// クトゥルフ神話TRPG（第6版）探索者作成用データ
// 技能・初期値は各年代の探索者シート、職業はルールブック p.48「職業のサンプル」に準拠。

const ERAS = {
  '1890': {
    label: '1890年代',
    sub: 'ガスライト',
    desc: 'ヴィクトリア朝末期。ガス灯と馬車、蒸気機関の時代。科学と迷信がせめぎ合い、心霊主義が流行している。',
    notes: '〈運転（馬車）〉〈操縦（気球／ボート）〉。〈精神分析〉〈コンピューター〉〈電子工学〉〈サブマシンガン〉はありません。',
  },
  '1920': {
    label: '1920年代',
    sub: 'クラシック',
    desc: 'ラヴクラフトが生きた狂騒の20年代。禁酒法、ジャズ、自動車と飛行機。クトゥルフ神話の標準的な舞台。',
    notes: '〈運転（自動車）〉〈精神分析〉〈サブマシンガン〉が使えます。〈コンピューター〉〈電子工学〉はありません。',
  },
  'modern': {
    label: '現代',
    sub: 'モダン',
    desc: 'スマートフォンとインターネットの時代。情報はすぐ手に入るが、真実ほど人目から隠されている。',
    notes: '〈コンピューター〉〈電子工学〉が追加されます。「ハッカー／コンサルタント」「スポークスマン」は現代のみ。',
  },
};

// 能力値（第6版）
const STATS = [
  { k: 'STR', n: '筋力',   dice: 3, plus: 0, hint: '腕力・体力' },
  { k: 'CON', n: '体力',   dice: 3, plus: 0, hint: '健康・持久力' },
  { k: 'POW', n: '精神力', dice: 3, plus: 0, hint: '意志・魔力' },
  { k: 'DEX', n: '敏捷性', dice: 3, plus: 0, hint: '素早さ・器用さ' },
  { k: 'APP', n: '外見',   dice: 3, plus: 0, hint: '魅力・容姿' },
  { k: 'SIZ', n: '体格',   dice: 2, plus: 6, hint: '身長・体重' },
  { k: 'INT', n: '知性',   dice: 2, plus: 6, hint: 'ひらめき・推理力' },
  { k: 'EDU', n: '教育',   dice: 3, plus: 3, hint: '知識・学歴' },
];

// 技能（第6版）
// base: 初期値（数値 or 能力値から計算する関数） / spec: 専門分野を持つ技能 / eras: 登場する年代（省略時は全年代）
// def: 年代ごとの初期の専門分野行
const SKILL_GROUPS = ['戦闘', '探索', '行動', '交渉', '知識'];
const SKILLS = [
  // 戦闘
  { k: 'dodge',     n: '回避',           g: '戦闘', base: s => s.DEX * 2, baseLabel: 'DEX×2' },
  { k: 'kick',      n: 'キック',         g: '戦闘', base: 25 },
  { k: 'grapple',   n: '組みつき',       g: '戦闘', base: 25 },
  { k: 'fist',      n: 'こぶし（パンチ）', g: '戦闘', base: 50 },
  { k: 'head',      n: '頭突き',         g: '戦闘', base: 10 },
  { k: 'throw',     n: '投擲',           g: '戦闘', base: 25 },
  { k: 'martial',   n: 'マーシャルアーツ', g: '戦闘', base: 1 },
  { k: 'handgun',   n: '拳銃',           g: '戦闘', base: 20 },
  { k: 'smg',       n: 'サブマシンガン', g: '戦闘', base: 15, eras: ['1920', 'modern'] },
  { k: 'shotgun',   n: 'ショットガン',   g: '戦闘', base: 30 },
  { k: 'mg',        n: 'マシンガン',     g: '戦闘', base: 15 },
  { k: 'rifle',     n: 'ライフル',       g: '戦闘', base: 25 },
  // 探索
  { k: 'firstaid',  n: '応急手当',       g: '探索', base: 30 },
  { k: 'locksmith', n: '鍵開け',         g: '探索', base: 1 },
  { k: 'conceal',   n: '隠す',           g: '探索', base: 15 },
  { k: 'hide',      n: '隠れる',         g: '探索', base: 10 },
  { k: 'listen',    n: '聞き耳',         g: '探索', base: 25 },
  { k: 'sneak',     n: '忍び歩き',       g: '探索', base: 10 },
  { k: 'photo',     n: '写真術',         g: '探索', base: 10 },
  { k: 'psychoanal',n: '精神分析',       g: '探索', base: 1, eras: ['1920', 'modern'] },
  { k: 'track',     n: '追跡',           g: '探索', base: 10 },
  { k: 'climb',     n: '登攀',           g: '探索', base: 40 },
  { k: 'library',   n: '図書館',         g: '探索', base: 25 },
  { k: 'spot',      n: '目星',           g: '探索', base: 25 },
  // 行動
  { k: 'drive',     n: '運転',           g: '行動', base: 20, spec: true, def: { '1890': ['馬車'], '1920': ['自動車'], 'modern': ['自動車'] } },
  { k: 'mechrep',   n: '機械修理',       g: '行動', base: 20 },
  { k: 'heavy',     n: '重機械操作',     g: '行動', base: 1 },
  { k: 'ride',      n: '乗馬',           g: '行動', base: 5 },
  { k: 'swim',      n: '水泳',           g: '行動', base: 25 },
  { k: 'craft',     n: '製作',           g: '行動', base: 5, spec: true, def: { all: [''] } },
  { k: 'pilot',     n: '操縦',           g: '行動', base: 1, spec: true, def: { '1890': ['気球', 'ボート'], '1920': [''], 'modern': [''] } },
  { k: 'jump',      n: '跳躍',           g: '行動', base: 25 },
  { k: 'elecrep',   n: '電気修理',       g: '行動', base: 10 },
  { k: 'navigate',  n: 'ナビゲート',     g: '行動', base: 10 },
  { k: 'disguise',  n: '変装',           g: '行動', base: 1 },
  // 交渉
  { k: 'fasttalk',  n: '言いくるめ',     g: '交渉', base: 5 },
  { k: 'credit',    n: '信用',           g: '交渉', base: 15 },
  { k: 'persuade',  n: '説得',           g: '交渉', base: 15 },
  { k: 'bargain',   n: '値切り',         g: '交渉', base: 5 },
  { k: 'ownlang',   n: '母国語',         g: '交渉', base: s => s.EDU * 5, baseLabel: 'EDU×5', spec: true, def: { all: [''] } },
  { k: 'lang',      n: 'ほかの言語',     g: '交渉', base: 1, spec: true, def: { all: [''] } },
  // 知識
  { k: 'medicine',  n: '医学',           g: '知識', base: 5 },
  { k: 'occult',    n: 'オカルト',       g: '知識', base: 5 },
  { k: 'chem',      n: '化学',           g: '知識', base: 1 },
  { k: 'mythos',    n: 'クトゥルフ神話', g: '知識', base: 0, locked: true },
  { k: 'art',       n: '芸術',           g: '知識', base: 5, spec: true, def: { all: [''] } },
  { k: 'account',   n: '経理',           g: '知識', base: 10 },
  { k: 'archaeo',   n: '考古学',         g: '知識', base: 1 },
  { k: 'computer',  n: 'コンピューター', g: '知識', base: 1, eras: ['modern'] },
  { k: 'psych',     n: '心理学',         g: '知識', base: 5 },
  { k: 'anthro',    n: '人類学',         g: '知識', base: 1 },
  { k: 'bio',       n: '生物学',         g: '知識', base: 1 },
  { k: 'geo',       n: '地質学',         g: '知識', base: 1 },
  { k: 'electro',   n: '電子工学',       g: '知識', base: 1, eras: ['modern'] },
  { k: 'astro',     n: '天文学',         g: '知識', base: 1 },
  { k: 'natural',   n: '博物学',         g: '知識', base: 10 },
  { k: 'physics',   n: '物理学',         g: '知識', base: 1 },
  { k: 'law',       n: '法律',           g: '知識', base: 5 },
  { k: 'pharm',     n: '薬学',           g: '知識', base: 1 },
  { k: 'history',   n: '歴史',           g: '知識', base: 20 },
];

// 専門分野の入力例
const SPEC_HINTS = {
  drive: '自動車、馬車、バイク など',
  craft: '料理、木工、裁縫、陶芸 など',
  pilot: '航空機、船舶、気球 など',
  ownlang: '日本語、英語 など',
  lang: '英語、ラテン語、中国語 など',
  art: '絵画、音楽、文学、演技 など',
};

// 職業（ルールブック p.48「職業のサンプル」）
// skills: 技能キー、または { k, s }（専門分野つき）
// choose: [{ n: 選ぶ数, of: [技能キー] }] / any: 自由に選べる技能の数（個人的あるいはその時代の特色的な技能）
// star: ラヴクラフトの小説によく登場する職業（ルールブックの星印）
const OCCUPATIONS = [
  { id: 'doctor', name: '医師', star: true,
    desc: '一般医、外科医、精神科医など。患者を救うことと、社会的な名声の両方を求める知的専門職。検死や薬品の知識が探索で活きる。',
    skills: ['medicine', 'firstaid', 'credit', 'psych', 'psychoanal', 'bio', { k: 'lang', s: 'ラテン語' }, 'pharm'], any: 1 },
  { id: 'engineer', name: 'エンジニア',
    desc: '機械・電気・土木などの技術者。理論と実践の両面から物事の仕組みを解き明かす。',
    skills: ['chem', 'mechrep', 'heavy', 'elecrep', 'geo', 'library', 'physics'], any: 1 },
  { id: 'entertainer', name: 'エンターテイナー',
    desc: '俳優、歌手、踊り子、芸人など、観客の前で芸を見せて生計を立てる人々。人に見られ、喝采を浴びるのが何より好き。',
    skills: ['fasttalk', 'dodge', 'listen', 'art', 'credit', 'psych', 'disguise'], any: 1 },
  { id: 'professor', name: '教授', star: true,
    desc: '大学で講義と研究を行う学者。博士号を持ち、専門分野では権威だが、専門外にはまるで疎いこともある。',
    skills: ['credit', 'psych', 'persuade', 'library', 'bargain', 'lang'],
    choose: [{ n: 2, of: ['medicine', 'chem', 'archaeo', 'anthro', 'bio', 'geo', 'electro', 'astro', 'natural', 'physics', 'law', 'history'] }] },
  { id: 'zealot', name: '狂信者',
    desc: '信念のためなら安楽な生活も捨てる活動家。意志が固く執念深い。暴力に訴える者もいれば、平和的に扇動する者もいる。',
    skills: ['conceal', 'hide', 'psych', 'persuade', 'library'],
    choose: [{ n: 2, of: ['chem', 'elecrep', 'law', 'pharm', 'rifle'] }], any: 1 },
  { id: 'officer', name: '軍士官',
    desc: '部隊を指揮する将校。規律と統率力、兵站や法規の知識を備える。退役軍人として探索に加わることも多い。',
    skills: ['account', 'credit', 'psych', 'persuade', 'navigate', 'bargain', 'law'], any: 1 },
  { id: 'police', name: '警官',
    desc: '街をパトロールする制服警官。現場での荒事にも慣れており、市民を守る最前線に立つ。',
    skills: ['fasttalk', 'firstaid', 'dodge', 'grapple', 'psych', 'law'],
    choose: [{ n: 2, of: ['drive', 'ride', 'bargain', 'martial', 'spot'] }] },
  { id: 'detective', name: '刑事', star: true,
    desc: '事件の捜査を担当する警察官。証拠を集め、嘘の中から真実を見つけ出す。巡査時代の経験が捜査の土台。',
    skills: ['fasttalk', 'listen', 'psych', 'persuade', 'bargain', 'law', 'spot'], any: 1 },
  { id: 'artist', name: '芸術家',
    desc: '画家や彫刻家など、独自のヴィジョンを表現する人。エゴが強く、時に抜け目ない商才も見せる。',
    skills: ['fasttalk', 'art', 'photo', 'psych', 'craft', 'spot', 'history'], any: 1 },
  { id: 'antiquarian', name: '古物研究家', star: true,
    desc: '古書や骨董品を愛し、その来歴を調べることに情熱を注ぐ。怪しげな遺物に最初に触れてしまうのも彼らだ。',
    skills: ['art', 'craft', 'library', 'bargain', 'lang', 'spot', 'history'], any: 1 },
  { id: 'author', name: '作家', star: true,
    desc: '言葉で人間の感情や人生を描き出す。孤独な仕事で収入は不安定。怪奇な題材を追ううちに深入りすることも。',
    skills: ['occult', 'psych', 'persuade', 'library', 'lang', 'ownlang', 'history'], any: 1 },
  { id: 'journalist', name: 'ジャーナリスト', star: true,
    desc: '新聞・雑誌・放送の記者。その日の出来事を記録し論評する。スクープを求めて危険な現場にも踏み込む。',
    skills: ['fasttalk', 'photo', 'psych', 'persuade', 'library', 'ownlang', 'history'], any: 1 },
  { id: 'pi', name: '私立探偵',
    desc: '個人の依頼で調査を行う探偵。浮気調査や人探しが発端で、思わぬ怪事件に巻き込まれるのが定番。元警官も多い。',
    skills: ['fasttalk', 'locksmith', 'photo', 'psych', 'library', 'bargain', 'law'], any: 1 },
  { id: 'spokesman', name: 'スポークスマン', eras: ['modern'],
    desc: '企業や団体、政治家の広報担当。人前で話し、印象を操作し、ときに都合の悪い事実をうまく隠す。',
    skills: ['fasttalk', 'dodge', 'credit', 'psych', 'persuade', 'disguise'], any: 1 },
  { id: 'athlete', name: 'スポーツ選手',
    desc: '鍛え抜かれた肉体を持つ運動選手。プロでもアマチュアでも、身体能力の高さは探索で頼りになる。',
    skills: ['dodge', 'ride', 'swim', 'jump', 'throw', 'climb', 'martial'], any: 1 },
  { id: 'clergy', name: '聖職者',
    desc: '神父、牧師、僧侶など。人々の悩みを聞き、教会の記録や古い文献に通じている。',
    skills: ['listen', 'account', 'psych', 'persuade', 'library', 'lang', 'history'], any: 1 },
  { id: 'parapsych', name: '超心理学者',
    desc: '超常現象を科学的に研究する者。神秘を信じる心と、科学者としての疑いの目が同居している。',
    skills: ['occult', 'anthro', 'photo', 'psych', 'library', 'lang', 'history'], any: 1 },
  { id: 'dilettante', name: 'ディレッタント', star: true,
    desc: '働かずとも暮らせる資産家。高い教育を受け、趣味や道楽に打ち込む。好奇心から怪事件に首を突っ込む。',
    skills: ['art', 'ride', 'shotgun', 'credit', 'craft', 'lang'], any: 2 },
  { id: 'missionary', name: '伝道者',
    desc: '神の教えを世界に広める宣教師。僻地での奉仕のため、医療や機械の心得を持つ。',
    skills: ['medicine', 'firstaid', 'mechrep', 'art', 'persuade', 'natural'], any: 1 },
  { id: 'tribe', name: 'トライブ・メンバー',
    desc: '血縁と慣習を重んじる部族の一員。自然と共に生き、伝承や土地の秘密に通じている。',
    skills: ['occult', 'listen', 'swim', 'throw', 'bargain', 'natural', 'spot'], any: 1 },
  { id: 'farmer', name: '農林業作業者',
    desc: '農夫、木こり、牧場主など。土地に根ざして暮らし、機械の扱いや自然の知識に長ける。',
    skills: ['firstaid', 'mechrep', 'heavy', 'craft', 'track', 'elecrep', 'natural'], any: 1 },
  { id: 'pilot', name: 'パイロット',
    desc: '航空機や船舶の操縦士。機械への深い理解と、航法・天候を読む技術を持つ。',
    skills: ['mechrep', 'heavy', 'elecrep', 'pilot', 'astro', 'navigate', 'physics'], any: 1 },
  { id: 'hacker', name: 'ハッカー／コンサルタント', eras: ['modern'],
    desc: 'コンピューターとネットワークの専門家。電子の海から情報を引き出す、現代の探索者。',
    skills: ['fasttalk', 'computer', 'elecrep', 'electro', 'library', 'physics', 'lang'], any: 1 },
  { id: 'criminal', name: '犯罪者',
    desc: '泥棒、詐欺師、密輸業者など法の外で生きる者。裏社会のコネと手癖の悪さが武器。',
    skills: ['fasttalk', 'locksmith', 'handgun', 'sneak', 'bargain', 'disguise', 'spot'], any: 1 },
  { id: 'soldier', name: '兵士',
    desc: '軍隊で訓練を受けた兵卒。戦場を生き延びた経験は、怪物との遭遇でも役立つかもしれない。',
    skills: ['firstaid', 'dodge', 'conceal', 'mechrep', 'listen', 'sneak', 'rifle'], any: 1 },
  { id: 'lawyer', name: '弁護士',
    desc: '法律の専門家。依頼人のために弁論し、交渉し、書類の山から突破口を見つける。',
    skills: ['fasttalk', 'credit', 'psych', 'persuade', 'library', 'bargain', 'law'], any: 1 },
  { id: 'drifter', name: '放浪者',
    desc: '定職も住まいも持たず各地を渡り歩く。社会の底辺から、誰も気づかない異変を目にする。',
    skills: ['fasttalk', 'hide', 'listen', 'sneak', 'psych', 'bargain', 'natural'], any: 1 },
  { id: 'musician', name: 'ミュージシャン',
    desc: '演奏家、作曲家、流しの歌い手など。音楽で生計を立て、酒場から社交界まで幅広く出入りする。',
    skills: ['fasttalk', 'listen', 'art', 'craft', 'persuade', 'psych', 'bargain'], any: 1 },
];

// バックグラウンド入力欄
const BACKGROUND_FIELDS = [
  { k: 'looks',     n: '容姿・外見の特徴', ph: '背が高く痩せている。左頬に古い傷跡。いつも古びたツイードのコートを着ている。' },
  { k: 'personality', n: '性格', ph: '物静かだが好奇心が強い。一度疑問を持つと納得するまで調べ続ける。', chips: true },
  { k: 'history',   n: '経歴・生い立ち', ph: 'どこで生まれ、どう育ち、なぜ今の職業に就いたのか。' },
  { k: 'family',    n: '家族・恋人・友人', ph: '両親は健在。妹が一人。大学時代の親友とは今も手紙をやりとりしている。' },
  { k: 'belief',    n: '信条・信仰・モットー', ph: '「真実はいつも記録の中にある」' },
  { k: 'treasure',  n: '大切なもの・こだわり', ph: '亡き父の懐中時計。' },
  { k: 'hobby',     n: '趣味・特技', ph: '古地図の収集、チェス。' },
  { k: 'fear',      n: '苦手なもの・恐れているもの', ph: '閉所、深い水。' },
  { k: 'scars',     n: '傷痕・精神的な障害', ph: '（キーパーと相談のうえ記入）' },
  { k: 'hook',      n: '探索に関わるきっかけ', ph: '恩師から届いた、意味の分からない手紙。' },
  { k: 'memo',      n: 'メモ', ph: '所持品、収入・財産、キーパーへの連絡事項など。' },
];

const PERSONALITY_WORDS = [
  '物静か', '陽気', '皮肉屋', 'お人好し', '頑固', '臆病', '勇敢', '几帳面', '大雑把', '好奇心旺盛',
  '冷静沈着', '短気', '慎重', '楽天的', '悲観的', '正義感が強い', '世話焼き', '無愛想', '気まぐれ', '知りたがり',
  '礼儀正しい', '神経質', '直感的', '理屈っぽい', '人見知り', '面倒見がよい', '見栄っ張り', '誠実',
];
